# Generated by Django 4.1.3 on 2023-10-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_order_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
    ]
